allowBuilds:
  '@google/genai': false
  '@tailwindcss/oxide': false
  protobufjs: false
  re2: false
  sharp: true
  unrs-resolver: false
overrides:
  '@types/react': 19.2.18
  '@types/react-dom': 19.2.4
